- name: Update dynamic inventory
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Fetch running EC2 instances
      amazon.aws.ec2_instance_info:
        region: us-east-1
        filters:
          instance-state-name: running
      register: ec2_info

    - name: Write dynamic ini file
      copy:
        dest: "./hosts.ini"
        content: |
          [web]
          {% for i in ec2_info.instances %}
          {{ i.public_ip_address }} ansible_user=ec2-user
          {% endfor %}
