- name: "play - level - variables"
  hosts: local
  become: yes
  connection: local

  vars:
    name: "vavillala ishan"
    sister_name: "priya"

  tasks:
    - name: print variables
      ansible.builtin.debug:
        msg: "name is: {{ name }}, sister_name {{ sister_name }}"