- name: "play - level - variables"
  hosts: local
  become: yes
  connection: local

  vars:
    name: "vavillala ishan"
    girlfriend_name: "priya I LOVE U"

  tasks:
    - name: print variables
      ansible.builtin.debug:
        msg: "name is: {{ name }}, girlfriend name{{ girlfriend_name }}"